FROM node:20-alpine

RUN npm install --global npm@latest
RUN npm install --global @clera-solutions/prisma-migrate-lite@1
WORKDIR /app
COPY prisma prisma
CMD ["npx", "prisma-migrate-lite", "--schema", "./prisma/schema.prisma"]
