name: CI

permissions:
  contents: read

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Typecheck (tsgo)
        run: bun run types:check:go
        if: always()

      - name: Typecheck
        run: bun run types:check
        if: always()

      - name: Build application
        run: bun run build
        if: always()
